-   id: pyproject-fmt
    name: pyproject-fmt
    description: ''
    entry: pyproject-fmt
    language: python
    'files': (^|/)pyproject\.toml$
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
