version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "1.75"
  jobs:
    post_create_environment:
      - pip install uv
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install --upgrade pip setuptools
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install --upgrade sphinx readthedocs-sphinx-ext
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install .[docs]

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
