name: Mirror
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "30 8 * * *"

jobs:
  build:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: git config --global user.name 'Github Actions'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
      - run: >-
          uvx -p 3.13 --from pre-commit-mirror-maker pre-commit-mirror . \
            --language=python --package-name=pyproject-fmt --files-regex '(^|/)pyproject\.toml$'
      - run: |
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
          git push origin HEAD:refs/heads/main --tags -f
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
