name: Mirror
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  mirror:
    permissions:
      contents: write
    environment:
      name: mirror
    runs-on: ubuntu-latest
    steps:
      - uses: tox-dev/action-pre-commit-mirrorer/mirror@main
        with:
          project: "pyproject-fmt"
          token: ${{ secrets.PA_TOKEN }}
